language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g grunt-cli@"0.1.13"

script:
  - grunt

addons:
  firefox: "30.0"
